# Generated by Django 4.0.5 on 2022-06-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='course.course'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='course.course'),
        ),
    ]
